development:
  adapter: postgresql
  database: falling_lava_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

test:
  adapter: postgresql
  database: falling_lava_test
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres

production:
  adapter: postgresql
  database: falling_lava_production
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres